# Generated by Django 2.1.7 on 2019-03-29 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adega', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='nome',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='venda',
            name='data',
            field=models.DateField(),
        ),
    ]
